# Generated by Django 3.2.5 on 2021-08-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'UserAnswer', 'verbose_name_plural': 'UserAnswers'},
        ),
        migrations.AlterModelOptions(
            name='userquestionnaire',
            options={'verbose_name': 'UserQuestionnaire', 'verbose_name_plural': 'UserQuestionnaires'},
        ),
        migrations.RenameField(
            model_name='userquestionnaire',
            old_name='right_answer',
            new_name='right_answers',
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Неправильные ответы'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='right',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ пользователя'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.userquestionnaire', verbose_name='Вариант пользователя'),
        ),
    ]
