# Generated by Django 3.2.5 on 2021-10-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='carattachment',
            order_with_respect_to='cars',
        ),
        migrations.AlterOrderWithRespectTo(
            name='car',
            order_with_respect_to='owner',
        ),
    ]
