# Generated by Django 3.2.5 on 2021-10-19 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=500, verbose_name='Имя принтера')),
                ('model', models.CharField(max_length=1000, verbose_name='Модель')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': ('Принтер',),
                'verbose_name_plural': ('Принтеры',),
                'order_with_respect_to': 'owner',
            },
        ),
        migrations.CreateModel(
            name='PrinterAttachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('file', models.FileField(upload_to='printers', verbose_name='Влажения')),
                ('printers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='printers.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': ('Влажения принтера',),
                'verbose_name_plural': ('Влажение принтеров',),
                'order_with_respect_to': 'printers',
            },
        ),
    ]
